name: evolvepro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - biopython
  - pip
  - openpyxl
  - pytorch
  - pip:
    - -e .
    - argparse
    - ankh
    - fair-esm
    - jax-unirep
    - transformers
    - git+https://github.com/nadavbra/protein_bert.git
